    api_key="8B86xeO8aV6pSZ9W3OqjihyeStsSxe06UIY0ku0RsPivUBIhvISnJQQJ99BDACHYHv6XJ3w3AAAAACOGf8nS"
    api_version="2024-10-21"
    azure_endpoint="https://globa-m99lmcki-eastus2.cognitiveservices.azure.com/"

